### ISSUE TITLE
User can view the company branding.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/sage-home-care#1]
# Motivation

Users should immediately see company branding via a logo placed near the top of the page.

# Tasks

- [x] Configure linters
- [x] Create HTML and CSS files
- [x] Create element for page background
- [x] Add logo to nav bar
- [x] Change background color to black
- [x] Position and style logo
